import streamlit as st
from docx import Document
from fpdf import FPDF
import io

st.title("AI Resume PRO")
st.write("By Dileep")

name = st.text_input("Name","Dileep Kumar M")
role = st.text_input("Role","Software Engineer")
email = st.text_input("Email","dileep@gmail.com")
phone = st.text_input("Phone","+91 98765")
skills = st.text_area("Skills","Python, Java, SQL")
exp = st.text_area("Exp","Software Engineer")
edu = st.text_input("Edu","B.Tech CSE")

if st.button("Generate"):
    st.success("Ready!")
    
    doc = Document()
    doc.add_heading(name,0)
    doc.add_paragraph(role)
    doc.add_paragraph(email)
    doc.add_paragraph(phone)
    doc.add_heading("Skills",2)
    doc.add_paragraph(skills)
    doc.add_heading("Exp",2)
    doc.add_paragraph(exp)
    doc.add_heading("Edu",2)
    doc.add_paragraph(edu)
    b1 = io.BytesIO()
    doc.save(b1)
    
    pdf = FPDF()
    pdf.add_page()
    pdf.set_fill_color(37,99,235)
    pdf.rect(0,0,210,35,'F')
    pdf.set_y(10)
    pdf.set_text_color(255,255,255)
    pdf.set_font("Arial","B",16)
    pdf.cell(0,10,name,align='C',ln=True)
    pdf.set_font("Arial","",10)
    pdf.cell(0,8,role,align='C',ln=True)
    pdf.cell(0,8,email,align='C',ln=True)
    pdf.set_y(40)
    pdf.set_text_color(0,0,0)
    pdf.set_x(15)
    pdf.set_font("Arial","B",11)
    pdf.cell(0,10,"SKILLS",ln=True)
    pdf.set_x(15)
    pdf.set_font("Arial","",10)
    pdf.multi_cell(180,6,skills)
    pdf.set_x(15)
    pdf.set_font("Arial","B",11)
    pdf.cell(0,10,"EXPERIENCE",ln=True)
    pdf.set_x(15)
    pdf.set_font("Arial","",10)
    pdf.multi_cell(180,6,exp)
    pdf.set_x(15)
    pdf.set_font("Arial","B",11)
    pdf.cell(0,10,"EDUCATION",ln=True)
    pdf.set_x(15)
    pdf.set_font("Arial","",10)
    pdf.multi_cell(180,6,edu)
    out = pdf.output()
    b2 = io.BytesIO(out)
    
    st.download_button("DOCX",b1.getvalue(),"resume.docx")
    st.download_button("PDF",b2.getvalue(),"resume.pdf")