import streamlit as st
from docx import Document
import io

st.set_page_config(page_title="AI Resume Maker", page_icon="📄")

st.title("AI Resume Maker")
st.markdown("Create professional ATS-friendly resumes in seconds!")

name = st.text_input("Full Name")
role = st.text_input("Target Role (e.g. Software Engineer)")
skills = st.text_area("Your Skills (comma separated)")
experience = st.text_area("Experience Details")

if st.button("Generate Resume"):
    if name and role:
        resume_text = f"""
        {name.upper()}
        {role}

        SKILLS: {skills}
        
        EXPERIENCE:
        {experience}
        
        Generated by AI Resume Maker
        """
        st.success("Resume Generated!")
        st.code(resume_text)
        
        # Create docx
        doc = Document()
        doc.add_heading(name, 0)
        doc.add_paragraph(role)
        doc.add_heading('Skills', level=1)
        doc.add_paragraph(skills)
        doc.add_heading('Experience', level=1)
        doc.add_paragraph(experience)
        
        bio = io.BytesIO()
        doc.save(bio)
        
        st.download_button(
            label="Download as DOCX",
            data=bio.getvalue(),
            file_name=f"{name}_Resume.docx",
            mime="docx"
        )
    else:
        st.warning("Please enter Name and Role da!")